name: Terraform Deployment from External Repository

on:
  workflow_dispatch:
    inputs:
      vpc_cidr:
        description: 'CIDR block for VPC'
        required: true
        default: '10.0.0.0/16'
      vpc_name:
        description: 'Name of the VPC'
        required: true
        default: 'my-vpc'
      bucket_name:
        description: 'S3 Bucket Name'
        required: true
        default: 'my-terraform-bucket'
      ami:
        description: 'AMI ID'
        required: true
        default: 'ami-12345678'
      instance_type:
        description: 'EC2 Instance Type'
        required: true
        default: 't2.micro'
      asg_name:
        description: 'Auto Scaling Group Name'
        required: true
        default: 'my-asg'
      min_size:
        description: 'Minimum Size of ASG'
        required: true
        default: '1'
      max_size:
        description: 'Maximum Size of ASG'
        required: true
        default: '3'
      subnet_ids:
        description: 'Comma separated list of Subnet IDs'
        required: true
        default: 'subnet-12345,subnet-67890'
      instance_name:
        description: 'Name of the EC2 Instance'
        required: true
        default: 'my-instance'  # Provide a default value if possible

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      # Clone the Terraform repository
      - name: Clone Terraform Repository
        run: |
          git clone --branch main https://$GITHUB_ACTOR:${{ secrets.TERRAFORM_REPO_TOKEN }}@github.com/Vikasvk17/module-input-github-action-ymal.git terraform-code
          cd terraform-code

      # Set environment variables for Terraform
      - name: Set Environment Variables for Terraform
        run: |
          echo "vpc_cidr=${{ github.event.inputs.vpc_cidr }}" >> $GITHUB_ENV
          echo "vpc_name=${{ github.event.inputs.vpc_name }}" >> $GITHUB_ENV
          echo "bucket_name=${{ github.event.inputs.bucket_name }}" >> $GITHUB_ENV
          echo "ami=${{ github.event.inputs.ami }}" >> $GITHUB_ENV
          echo "instance_type=${{ github.event.inputs.instance_type }}" >> $GITHUB_ENV
          echo "asg_name=${{ github.event.inputs.asg_name }}" >> $GITHUB_ENV
          echo "min_size=${{ github.event.inputs.min_size }}" >> $GITHUB_ENV
          echo "max_size=${{ github.event.inputs.max_size }}" >> $GITHUB_ENV
          echo "subnet_ids=${{ github.event.inputs.subnet_ids }}" >> $GITHUB_ENV
          echo "instance_name=${{ github.event.inputs.instance_name }}" >> $GITHUB_ENV

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform-code

      # Run terraform plan with passed input values
      - name: Run Terraform Plan
        run: |
          terraform plan \
            -var "vpc_cidr=${{ github.event.inputs.vpc_cidr }}" \
            -var "vpc_name=${{ github.event.inputs.vpc_name }}" \
            -var "bucket_name=${{ github.event.inputs.bucket_name }}" \
            -var "ami=${{ github.event.inputs.ami }}" \
            -var "instance_type=${{ github.event.inputs.instance_type }}" \
            -var "asg_name=${{ github.event.inputs.asg_name }}" \
            -var "min_size=${{ github.event.inputs.min_size }}" \
            -var "max_size=${{ github.event.inputs.max_size }}" \
            -var "subnet_ids=${{ github.event.inputs.subnet_ids }}" \
            -var "instance_name=${{ github.event.inputs.instance_name }}"
        working-directory: ./terraform-code

      # Apply terraform plan
      - name: Apply Terraform Plan
        run: |
          terraform apply -auto-approve \
            -var "vpc_cidr=${{ github.event.inputs.vpc_cidr }}" \
            -var "vpc_name=${{ github.event.inputs.vpc_name }}" \
            -var "bucket_name=${{ github.event.inputs.bucket_name }}" \
            -var "ami=${{ github.event.inputs.ami }}" \
            -var "instance_type=${{ github.event.inputs.instance_type }}" \
            -var "asg_name=${{ github.event.inputs.asg_name }}" \
            -var "min_size=${{ github.event.inputs.min_size }}" \
            -var "max_size=${{ github.event.inputs.max_size }}" \
            -var "subnet_ids=${{ github.event.inputs.subnet_ids }}" \
            -var "instance_name=${{ github.event.inputs.instance_name }}"
        working-directory: ./terraform-code
