name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VARS: |
        {
          "vpc_cidr": "10.0.0.0/16",
          "vpc_name": "my-vpc",
          "bucket_name": "my-terraform-bucket",
          "ami": "ami-12345678",
          "instance_type": "t2.micro",
          "instance_name": "my-instance",
          "asg_name": "my-asg",
          "min_size": 1,
          "max_size": 3,
          "subnet_ids": ["subnet-12345", "subnet-67890"]
        }
      TERRAFORM_REPO_URL: "https://github.com/your-org/terraform-repo.git"
      TERRAFORM_REPO_BRANCH: "main"

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Clone Terraform Repository
        run: |
          git clone --branch $TERRAFORM_REPO_BRANCH $TERRAFORM_REPO_URL terraform-code
          cd terraform-code

      - name: Parse Terraform Variables
        id: parse_vars
        run: |
          echo "PARSED_VARS=$(echo '${TF_VARS}' | jq -r 'to_entries | map("--var \(.key)=\(.value|tostring)") | join(" ")')" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform-code

      - name: Plan Terraform
        run: terraform plan $PARSED_VARS
        working-directory: ./terraform-code

      - name: Apply Terraform
        run: terraform apply -auto-approve $PARSED_VARS
        working-directory: ./terraform-code
